Fixed bug where output X0,Y0 parameters in bootstrap-resampling and MCMC output did not correct for image offsets (i.e., when only a subsection of the input data image is fit).
Added internal vector<mp_par> variable to ModelObject, set by AddParameterInfo method;
converted PrintModelParams updated PrintModelParams and PrintModelParamsToString methods
to use this instead of an input parameter; updated print_results.cpp to use new interfaces.

Updated regression tests to count and report number of failed tests and to use colored
output more simply & consistently; modified Python testing functions (compare_fits_files.py,
diff_printouts.py) to report errors with colored text and to return 0 or 1 to shell for
success or failure, respectively.

diff --git a/do_imfit_tests b/do_imfit_tests
--- a/do_imfit_tests
+++ b/do_imfit_tests
@@ -7,6 +7,13 @@
 # Including DE and oversampled-PSF tests: run script as
 # $ ./do_imfit_tests --all
 
+# Predefine some ANSI color escape codes
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+
+# create an integer variable for status (& counting number of failed tests)
+declare -i STATUS=0
+
 FAILED_TEXT=" ** Test failed. **"
 
 do_fits_tests=$(./python/py_startup_test.py)
@@ -21,8 +28,6 @@ case "$OSTYPE" in
   linux*)   osname="linux" ;;
   *)        echo "unknown: $OSTYPE" ;;
 esac
-
-STATUS=0
 
 # create output directory for test_dump*, etc. files (will do nothing if
 # directory already exists), then delete existing test_dump* files
@@ -96,9 +101,11 @@ echo -n "   (now running Cash-statistic and Poisson MLR fits ...)"
 ./imfit tests/pgc35772_continuum.fits[340:630,300:580] -c tests/config_imfit_pgc35772.dat --mask=tests/pgc35772_mask.fits[340:630,300:580] --mlr  &> temptest/test_dump5d
 echo ""
 
-# test bootstrap resampling (just to see that program doesn't crash)
+# test bootstrap resampling (first is just to see that program doesn't crash, which happened
+# previously when nIterations = 3; third is for testing that we correct for image offsets)
 ./imfit tests/ic3478rss_64x64.fits -c tests/imfit_config_ic3478_64x64b.dat --bootstrap 3 &> /dev/null
-./imfit tests/ic3478rss_64x64.fits -c tests/imfit_config_ic3478_64x64b.dat --bootstrap 3 --save-bootstrap temp_bootstrap_output.dat &> /dev/null
+./imfit tests/ic3478rss_64x64.fits -c tests/imfit_config_ic3478_64x64b.dat --seed 10 --bootstrap 5 --save-bootstrap temptest/temp_bootstrap_output.dat &> /dev/null
+./imfit tests/ic3478rss_64x64.fits[10:64,10:64] -c tests/imfit_config_ic3478_64x64b.dat --seed 10 --bootstrap 5 --save-bootstrap temptest/temp_bootstrap_output2.dat &> /dev/null
 
 # testing error-image generation and saving
 # first using data values for errors, then using model values (should be identical)
@@ -164,15 +171,19 @@ echo ""
 
 echo -n "*** Diff comparison with archives: first test... "
 ./python/diff_printouts.py tests/imfit_textout1 temptest/test_dump1 --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: tiny SDSS cutout image... "
 ./python/diff_printouts.py tests/imfit_textout2 temptest/test_dump2 --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: tiny SDSS cutout image (take 2)... "
 ./python/diff_printouts.py tests/imfit_textout3 temptest/test_dump3 --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: tiny SDSS cutout image (N-M simplex fit)... "
 ./python/diff_printouts.py tests/imfit_textout3b temptest/test_dump3b --skip-last=3
+STATUS+=$?
 
 # special test for DE output because final parameter are more variable from one fit
 # to the next...
@@ -181,69 +192,96 @@ then
   tail -n 17 temptest/test_dump3c > temptest/test_dump3c_tail
   echo -n "*** Comparison with archives (tolerances ~ 5e-5 or smaller): tiny SDSS cutout image (DE fit)... "
   ./python/compare_imfit_printouts.py temptest/test_dump3c_tail tests/imfit_textout3c_tail
+  STATUS+=$?
 fi
 
 echo -n "*** Diff comparison with archives: tiny SDSS cutout image (L-M fit with --loud)... "
 ./python/diff_printouts.py tests/imfit_textout3d temptest/test_dump3d --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: tiny SDSS cutout image (L-M fit with --loud, fixed parameter)... "
 ./python/diff_printouts.py tests/imfit_textout3d2 temptest/test_dump3d2 --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: tiny SDSS cutout image (L-M fit using sigma map)... "
 ./python/diff_printouts.py tests/imfit_textout3e temptest/test_dump3e --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: tiny SDSS cutout image (L-M fit using variance map)... "
 ./python/diff_printouts.py tests/imfit_textout3e2 temptest/test_dump3e2 --skip-last=3
+STATUS+=$?
 
 
 echo -n "*** Diff comparison with archives: fit to larger (rectangular) SDSS image w/ PSF convolution... "
 ./python/diff_printouts.py tests/imfit_textout4 temptest/test_dump4 --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: same, but using counts/sec image + --exptime option... "
 ./python/diff_printouts.py tests/imfit_textout4b temptest/test_dump4b --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: chisquare-only calculation... "
 ./python/diff_printouts.py tests/imfit_textout4c temptest/test_dump4c --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: chisquare-only (Cash statistic) calculation... "
 ./python/diff_printouts.py tests/imfit_textout4d temptest/test_dump4d --skip-last=3
+STATUS+=$?
 
 if [ "$1" == "--all" ]
 then
   echo -n "*** Diff comparison with archives: fit using oversampled PSF... "
   ./python/diff_printouts.py tests/imfit_textout4e temptest/test_dump4e --skip-last=3
+  STATUS+=$?
 
   echo -n "*** Diff comparison with archives: fit using oversampled PSF + image section... "
   ./python/diff_printouts.py tests/imfit_textout4e2 temptest/test_dump4e2 --skip-last=3
+  STATUS+=$?
 fi
 
 echo -n "*** Diff comparison with archives: fit using Cash statistic... "
 tail -n 18 temptest/test_dump5a > temptest/test_dump5a_tail
 ./python/diff_printouts.py tests/imfit_textout5a_tail temptest/test_dump5a_tail --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: fit using Poisson MLR statistic (+ N-M solver)... "
 tail -n 18 temptest/test_dump5b > temptest/test_dump5b_tail
 ./python/diff_printouts.py tests/imfit_textout5b_tail temptest/test_dump5b_tail --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: fit using Poisson MLR statistic (+ L-M solver)... "
 tail -n 18 temptest/test_dump5c > temptest/test_dump5c_tail
 ./python/diff_printouts.py tests/imfit_textout5c_tail temptest/test_dump5c_tail --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: Poisson-MLR-stat fit to problematic image (+ L-M solver)... "
 tail -n 18 temptest/test_dump5d > temptest/test_dump5d_tail
 ./python/diff_printouts.py tests/imfit_textout5d_tail temptest/test_dump5d_tail --skip-last=3
+STATUS+=$?
+
+echo -n "*** Diff comparison with archives: bootstrap-resampling output... "
+tail -n 7 temptest/temp_bootstrap_output.dat > temptest/temp_bootstrap_output_tail
+./python/diff_printouts.py tests/bootstrap_output_seed10_tail.dat temptest/temp_bootstrap_output_tail
+STATUS+=$?
+
+echo -n "*** Diff comparison with archives: bootstrap-resampling output (with image offset)... "
+tail -n 7 temptest/temp_bootstrap_output2.dat > temptest/temp_bootstrap_output2_tail
+./python/diff_printouts.py tests/bootstrap_output_seed10_2_tail.dat temptest/temp_bootstrap_output2_tail
+STATUS+=$?
 
 
 # do output weight images agree?
 if [ $do_fits_tests = "1" ]
 then
   ./python/compare_fits_files.py temptest/test_weights_data.fits temptest/test_weights_model.fits
+  STATUS+=$?
 fi
 
 # Does residual + model = original image?
 if [ $do_fits_tests = "1" ]
 then
   ./python/compare_fits_files.py --compare-sum temptest/test_residual_ic3478.fits temptest/test_model_ic3478.fits tests/ic3478rss_64x64.fits
+  STATUS+=$?
 fi
 
 echo -n "*** Diff comparison with archives: catching the case of masking all pixels... "
@@ -251,47 +289,59 @@ if (diff --brief temptest/test_dump6 tests/imfit_textout6)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump6 tests/imfit_textout6
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: catching the case of mismatch in data and mask sizes... "
 ./python/diff_printouts.py tests/imfit_textout6b temptest/test_dump6b
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: catching non-image FITS file (empty HDU) for data image... "
 ./python/diff_printouts.py tests/imfit_textout6c temptest/test_dump6c
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: catching non-image FITS file (table in HDU 1) for data image... "
 ./python/diff_printouts.py tests/imfit_textout6d temptest/test_dump6d
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: catching non-image FITS file (empty HDU) for mask image... "
 ./python/diff_printouts.py tests/imfit_textout6e temptest/test_dump6e
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: catching [0] referring to empty HDU... "
 ./python/diff_printouts.py tests/imfit_textout6f temptest/test_dump6f
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: correctly handling [1] referring to valid image in FITS file... "
 ./python/diff_printouts.py tests/imfit_textout6g temptest/test_dump6g --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: correctly handling [1] + image subsection... "
 ./python/diff_printouts.py tests/imfit_textout6h temptest/test_dump6h --skip-last=3
+STATUS+=$?
 
 
 echo -n "*** Diff comparison with archives: automatic masking of NaN values in data... "
 ./python/diff_printouts.py tests/imfit_textout7a temptest/test_dump7a --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: automatic masking of NaN values in mask... "
 ./python/diff_printouts.py tests/imfit_textout7b temptest/test_dump7b --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: automatic masking of NaN values in noise map... "
 ./python/diff_printouts.py tests/imfit_textout7c temptest/test_dump7c --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: detection of zero-valued pixel (bad for data-based chi^2 errors)... "
 ./python/diff_printouts.py tests/imfit_textout7d temptest/test_dump7d --skip-last=3
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: ignore zero-valued pixel when it's masked... "
 ./python/diff_printouts.py tests/imfit_textout7e temptest/test_dump7e --skip-last=3
+STATUS+=$?
 
 
 
@@ -301,9 +351,9 @@ if (diff --brief temptest/test_dump_bad1 tests/imfit_textout_bad1)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad1 tests/imfit_textout_bad1
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 2... "
@@ -311,9 +361,9 @@ if (diff --brief temptest/test_dump_bad2 tests/imfit_textout_bad2)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad2 tests/imfit_textout_bad2
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 3... "
@@ -321,9 +371,9 @@ if (diff --brief temptest/test_dump_bad3 tests/imfit_textout_bad3)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad3 tests/imfit_textout_bad3
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 4... "
@@ -331,9 +381,9 @@ if (diff --brief temptest/test_dump_bad4 tests/imfit_textout_bad4)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad4 tests/imfit_textout_bad4
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 5... "
@@ -341,9 +391,9 @@ if (diff --brief temptest/test_dump_bad5 tests/imfit_textout_bad5)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad5 tests/imfit_textout_bad5
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 6... "
@@ -351,9 +401,9 @@ if (diff --brief temptest/test_dump_bad6 tests/imfit_textout_bad6)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad6 tests/imfit_textout_bad6
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 7... "
@@ -361,9 +411,9 @@ if (diff --brief temptest/test_dump_bad7 tests/imfit_textout_bad7)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad7 tests/imfit_textout_bad7
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad parameter specification... "
@@ -371,9 +421,9 @@ if (diff --brief temptest/test_dump_bad8 tests/imfit_textout_bad8)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_bad8 tests/imfit_textout_bad7
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad --nlopt name... "
@@ -381,11 +431,24 @@ if (diff --brief temptest/test_dump_badnloptname tests/imfit_textout_badnloptnam
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   {$RED}Failed:{$NC} Diff output:"
   diff temptest/test_dump_badnloptname tests/imfit_textout_badnloptname
-  STATUS=1
+  STATUS+=1
 fi
 
+
+
+
+echo ""
+if [ $STATUS -eq 1 ]
+then
+  echo -e "${RED}One test failed!${NC}"
+elif [ $STATUS -gt 1 ]
+then
+  echo -e "${RED}${STATUS} tests failed!${NC}"
+else
+  echo "All tests passed."
+fi
 
 echo ""
 echo "Done."
diff --git a/do_makeimage_tests b/do_makeimage_tests
--- a/do_makeimage_tests
+++ b/do_makeimage_tests
@@ -2,6 +2,14 @@
 #
 # Regression tests for makeimage
 
+# Predefine some ANSI color escape codes
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+
+# create an integer variable for status (& counting number of failed tests)
+declare -i STATUS=0
+
+
 FAILED_TEXT=" ** Test failed. **"
 
 do_fits_tests=$(./python/py_startup_test.py)
@@ -25,8 +33,6 @@ case "$OSTYPE" in
   linux*)   osname="linux" ;;
   *)        echo "unknown: $OSTYPE" ;;
 esac
-
-STATUS=0
 
 # create output directory for test_dump*, etc. files (will do nothing if
 # directory already exists)
@@ -86,7 +92,7 @@ if (diff --brief temptest/test_dump0 tests/makeimage_textout0)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump0 tests/makeimage_textout0
   STATUS+=1
 fi
@@ -96,13 +102,14 @@ if (diff --brief temptest/test_dump1 tests/makeimage_textout1)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump1 tests/makeimage_textout1
-  STATUS=1
+  STATUS+=1
 fi
 if [ $do_fits_tests = "1" ]
 then
   ./python/compare_fits_files.py temptest/biggertest.fits tests/biggertest_orig.fits
+  STATUS+=$?
 fi
 
 echo -n "*** Diff comparison with archives: gensersictest... "
@@ -110,13 +117,14 @@ if (diff --brief temptest/test_dump2 tests/makeimage_textout2)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump2 tests/makeimage_textout2
-  STATUS=1
+  STATUS+=1
 fi
 if [ $do_fits_tests = "1" ]
 then
   ./python/compare_fits_files.py temptest/gensersictest.fits tests/gensersictest_orig.fits
+  STATUS+=$?
 fi
 
 echo -n "*** Diff comparison with archives: sersic + exponential... "
@@ -124,17 +132,19 @@ if (diff --brief temptest/test_dump3 tests/makeimage_textout3)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump3 tests/makeimage_textout3
-  STATUS=1
+  STATUS+=1
 fi
 if [ $do_fits_tests = "1" ]
 then
   ./python/compare_fits_files.py temptest/sersic+exp.fits tests/sersic+exp_orig.fits
+  STATUS+=$?
 fi
 if [ $do_fits_tests = "1" ]
 then
   ./python/compare_fits_files.py temptest/sersic+exp_b.fits tests/sersic+exp_orig.fits
+  STATUS+=$?
 fi
 
 echo -n "*** Diff comparison with archives: gensersictest + PSF convolution... "
@@ -144,13 +154,14 @@ if (diff --brief temptest/test_dump4 tests/makeimage_textout4)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump4 tests/makeimage_textout4
-  STATUS=1
+  STATUS+=1
 fi
 if [ $do_fits_tests = "1" ]
 then
   ./python/compare_fits_files.py temptest/gensersictest_conv.fits tests/gensersictest612_conv_cutout512.fits
+  STATUS+=$?
 fi
 
 if [ $do_fits_tests = "1" ]
@@ -158,6 +169,7 @@ if [ $do_fits_tests = "1" ]
   echo ""
 then
   ./python/compare_fits_files.py --compare-sum temptest/singleImage_conv1_Sersic.fits temptest/singleImage_conv2_Exponential.fits temptest/sersic+exp_conv.fits
+  STATUS+=$?
 fi
 
 
@@ -168,6 +180,7 @@ if [ $do_fits_tests = "1" ]
   echo ""
 then
   ./python/compare_fits_files.py temptest/oversampled.fits tests/${osname}/oversampled_orig.fits
+  STATUS+=$?
 fi
 
 if [ $do_fits_tests = "1" ]
@@ -175,6 +188,7 @@ if [ $do_fits_tests = "1" ]
   echo ""
 then
   ./python/compare_fits_files.py temptest/oversampled2both.fits tests/${osname}/oversampled2both_orig.fits
+  STATUS+=$?
 fi
 
 if [ $do_fits_tests = "1" ]
@@ -182,6 +196,7 @@ if [ $do_fits_tests = "1" ]
   echo ""
 then
   ./python/compare_fits_files.py temptest/oversampled2both_2psf.fits tests/${osname}/oversampled2both_orig.fits
+  STATUS+=$?
 fi
 
 
@@ -190,9 +205,9 @@ if (diff --brief temptest/test_dump5 tests/makeimage_textout5)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump5 tests/makeimage_textout5
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 1... "
@@ -200,9 +215,9 @@ if (diff --brief temptest/test_dump6 tests/makeimage_textout6)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump6 tests/makeimage_textout6
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 2... "
@@ -210,9 +225,9 @@ if (diff --brief temptest/test_dump7 tests/makeimage_textout7)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump7 tests/makeimage_textout7
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 3... "
@@ -220,9 +235,9 @@ if (diff --brief temptest/test_dump8 tests/makeimage_textout8)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump8 tests/makeimage_textout8
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 4... "
@@ -230,9 +245,9 @@ if (diff --brief temptest/test_dump9 tests/makeimage_textout9)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump9 tests/makeimage_textout9
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 5... "
@@ -240,9 +255,9 @@ if (diff --brief temptest/test_dump10 tests/makeimage_textout10)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump10 tests/makeimage_textout10
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 6... "
@@ -250,9 +265,9 @@ if (diff --brief temptest/test_dump11 tests/makeimage_textout11)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump11 tests/makeimage_textout11
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad reference file... "
@@ -260,9 +275,9 @@ if (diff --brief temptest/test_dump12 tests/makeimage_textout12)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump12 tests/makeimage_textout12
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad PSF-image file... "
@@ -270,9 +285,9 @@ if (diff --brief temptest/test_dump13 tests/makeimage_textout13)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump13 tests/makeimage_textout13
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: PSF-image file with NaN values... "
@@ -280,9 +295,9 @@ if (diff --brief temptest/test_dump13b tests/makeimage_textout13b)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump13b tests/makeimage_textout13b
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: non-existent PSF-image file... "
@@ -290,9 +305,9 @@ if (diff --brief temptest/test_dump14 tests/makeimage_textout14)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump14 tests/makeimage_textout14
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad parameter specification... "
@@ -300,9 +315,21 @@ if (diff --brief temptest/test_dump15 tests/makeimage_textout15)
 then
   echo " OK"
 else
-  echo -e "   \033[1;31m Failed: \033[0mDiff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff temptest/test_dump15 tests/makeimage_textout15
-  STATUS=1
+  STATUS+=1
+fi
+
+
+echo ""
+if [ $STATUS -eq 1 ]
+then
+  echo -e "${RED}One test failed!${NC}"
+elif [ $STATUS -gt 1 ]
+then
+  echo -e "${RED}${STATUS} tests failed!${NC}"
+else
+  echo "All tests passed."
 fi
 
 
@@ -311,4 +338,3 @@ echo "Done."
 echo ""
 
 exit $STATUS
-
diff --git a/do_mcmc_tests b/do_mcmc_tests
--- a/do_mcmc_tests
+++ b/do_mcmc_tests
@@ -3,9 +3,15 @@
 # Regression tests for imfit-mcmc
 #
 
+# Predefine some ANSI color escape codes
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+
+# create an integer variable for status (& counting number of failed tests)
+declare -i STATUS=0
+
 FAILED_TEXT=" ** Test failed. **"
 
-STATUS=0
 
 # create output directory for test_dump*, etc. files (will do nothing if
 # directory already exists)
@@ -36,6 +42,9 @@ echo ""
 ./imfit-mcmc -c tests/config_imfit_sersictest512_badlimits3.dat tests/ic3478rss_64x64.fits &> temptest/test_dump_bad7
 ./imfit-mcmc -c tests/config_imfit_badparamline.dat tests/ic3478rss_64x64.fits &> temptest/test_dump_bad8
 
+
+
+
 echo ""
 
 
@@ -45,6 +54,7 @@ echo ""
 printf "*** Diff comparison with archives: first test... "
 # skip last 4 lines to avoid trying to compare elapsed times
 ./python/diff_printouts.py temptest/test_dump_mcmc1 tests/mcmc_textout1 --skip-last=4
+STATUS+=$?
 
 printf "    Comparing first output chain file... "
 # skip first two lines of output file to avoid comparing timestamps
@@ -53,15 +63,17 @@ if (diff --brief temptest/mcmc_test.0.txt_skip2 tests/mcmc_ref1.0.txt_skip2)
 then
   printf " OK\n"
 else
-  echo "Output MCMC chain file temptest/mcmc_test.0.txt differs from reference file tests/mcmc_ref1.0.txt"
-  STATUS=1
+  echo -e "   ${RED}Failed:${NC}  Output MCMC chain file temptest/mcmc_test.0.txt differs from reference file tests/mcmc_ref1.0.txt"
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: catching the case of all data pixels masked... "
 ./python/diff_printouts.py tests/test_dump_mcmc2a temptest/test_dump2a
+STATUS+=$?
 
 echo -n "*** Diff comparison with archives: catching the case of mismatch in data and mask sizes... "
 ./python/diff_printouts.py tests/test_dump_mcmc2b temptest/test_dump2b
+STATUS+=$?
 
 
 # Note that for the following, we can compare with the imfit reference files,
@@ -72,9 +84,9 @@ if (diff --brief temptest/test_dump_bad1 tests/imfit_textout_bad1)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad1 tests/imfit_textout_bad1
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 2... "
@@ -82,9 +94,9 @@ if (diff --brief temptest/test_dump_bad2 tests/imfit_textout_bad2)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad2 tests/imfit_textout_bad2
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 3... "
@@ -92,9 +104,9 @@ if (diff --brief temptest/test_dump_bad3 tests/imfit_textout_bad3)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad3 tests/imfit_textout_bad3
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 4... "
@@ -102,9 +114,9 @@ if (diff --brief temptest/test_dump_bad4 tests/imfit_textout_bad4)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad4 tests/imfit_textout_bad4
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 5... "
@@ -112,9 +124,9 @@ if (diff --brief temptest/test_dump_bad5 tests/imfit_textout_bad5)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad5 tests/imfit_textout_bad5
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 6... "
@@ -122,9 +134,9 @@ if (diff --brief temptest/test_dump_bad6 tests/imfit_textout_bad6)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad6 tests/imfit_textout_bad6
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 7... "
@@ -132,9 +144,9 @@ if (diff --brief temptest/test_dump_bad7 tests/imfit_textout_bad7)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad7 tests/imfit_textout_bad7
-  STATUS=1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: bad parameter specification... "
@@ -142,11 +154,22 @@ if (diff --brief temptest/test_dump_bad8 tests/imfit_textout_bad8)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}  Diff output:"
   diff temptest/test_dump_bad7 tests/imfit_textout_bad7
-  STATUS=1
+  STATUS+=1
 fi
 
+
+echo ""
+if [ $STATUS -eq 1 ]
+then
+  echo -e "${RED}One test failed!${NC}"
+elif [ $STATUS -gt 1 ]
+then
+  echo -e "${RED}${STATUS} tests failed!${NC}"
+else
+  echo "All tests passed."
+fi
 
 echo ""
 echo "Done."
diff --git a/do_profilefit_tests b/do_profilefit_tests
--- a/do_profilefit_tests
+++ b/do_profilefit_tests
@@ -2,6 +2,13 @@
 #
 # Regression tests for profilefit
 
+# Predefine some ANSI color escape codes
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+
+# create an integer variable for status (& counting number of failed tests)
+declare -i STATUS=0
+
 FAILED_TEXT=" ** Test failed. **"
 
 echo ""
@@ -16,6 +23,8 @@ echo "Running tests for profilefit (L-M solver only)..."
 ./profilefit profile_data/n5831_total.dat tests/config_profilefit_sersic.dat --chisquare-only &> test_dump4
 
 
+
+
 echo ""
 
 echo -n "*** Diff comparison with archives: NGC 5381 Sersict fit... "
@@ -23,8 +32,9 @@ if (diff --brief test_dump1 tests/profilefit_textout1)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff test_dump1 tests/profilefit_textout1
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: NGC 3348 Core-Sersic fit... "
@@ -32,8 +42,9 @@ if (diff --brief test_dump2 tests/profilefit_textout2)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff test_dump2 tests/profilefit_textout2
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: NGC 5381 Sersict fit (Nelder-Mead Simplex)... "
@@ -42,8 +53,9 @@ if (diff --brief test_dump3a_tail tests/profilefit_textout3a)
 then
   echo " OK"
 else
-  echo "Diff output (last 11 lines):"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff test_dump3a_tail tests/profilefit_textout3a
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: NGC 5381 Sersict fit (Differential Evoln.)... "
@@ -52,8 +64,9 @@ if (diff --brief test_dump3b_tail tests/profilefit_textout3b)
 then
   echo " OK"
 else
-  echo "Diff output (last 11 lines):"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff test_dump3b_tail tests/profilefit_textout3b
+  STATUS+=1
 fi
 
 echo -n "*** Diff comparison with archives: NGC 5381 Sersict fit -- print initial chi^2 only... "
@@ -61,11 +74,26 @@ if (diff --brief test_dump4 tests/profilefit_textout4)
 then
   echo " OK"
 else
-  echo "Diff output:"
+  echo -e "   ${RED}Failed:${NC}Diff output:"
   diff test_dump4 tests/profilefit_textout4
+  STATUS+=1
+fi
+
+
+echo ""
+if [ $STATUS -eq 1 ]
+then
+  echo -e "${RED}One test failed!${NC}"
+elif [ $STATUS -gt 1 ]
+then
+  echo -e "${RED}${STATUS} tests failed!${NC}"
+else
+  echo "All tests passed."
 fi
 
 
 echo ""
 echo "Done."
 echo ""
+
+exit $STATUS
