Updated do_makeimage_tests to check for existence of ./makeimage before it runs tests; also returns 1 if any of the diff tests fail.

diff --git a/do_makeimage_tests b/do_makeimage_tests
--- a/do_makeimage_tests
+++ b/do_makeimage_tests
@@ -9,6 +9,17 @@ then
   echo -n "Tests will skip comparison of FITS files"
 fi
 
+
+if [ ! -f ./makeimage ]
+  then
+    echo "*** Unable to find local copy of makeimage! ***"
+    echo
+    exit 2
+fi
+
+
+STATUS = 0
+
 # create output directory for test_dump*, etc. files (will do nothing if
 # directory already exists)
 mkdir -p temptest
@@ -58,6 +69,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump0 tests/makeimage_textout0
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: biggertest... "
@@ -67,6 +79,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump1 tests/makeimage_textout1
+  STATUS = 1
 fi
 if [ $do_fits_tests = "1" ]
 then
@@ -80,6 +93,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump2 tests/makeimage_textout2
+  STATUS = 1
 fi
 if [ $do_fits_tests = "1" ]
 then
@@ -93,6 +107,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump3 tests/makeimage_textout3
+  STATUS = 1
 fi
 if [ $do_fits_tests = "1" ]
 then
@@ -112,6 +127,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump4 tests/makeimage_textout4
+  STATUS = 1
 fi
 if [ $do_fits_tests = "1" ]
 then
@@ -139,6 +155,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump5 tests/makeimage_textout5
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 1... "
@@ -148,6 +165,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump6 tests/makeimage_textout6
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 2... "
@@ -157,6 +175,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump7 tests/makeimage_textout7
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 3... "
@@ -166,6 +185,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump8 tests/makeimage_textout8
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 4... "
@@ -175,6 +195,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump9 tests/makeimage_textout9
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 5... "
@@ -184,6 +205,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump10 tests/makeimage_textout10
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad config file 6... "
@@ -193,6 +215,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump11 tests/makeimage_textout11
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad reference file... "
@@ -202,6 +225,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump12 tests/makeimage_textout12
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad PSF-image file... "
@@ -211,6 +235,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump13 tests/makeimage_textout13
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: non-existent PSF-image file... "
@@ -220,6 +245,7 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump14 tests/makeimage_textout14
+  STATUS = 1
 fi
 
 echo -n "*** Diff comparison with archives: bad parameter specification... "
@@ -229,9 +255,13 @@ then
 else
   echo "Diff output:"
   diff temptest/test_dump15 tests/makeimage_textout15
+  STATUS = 1
 fi
 
 
 echo ""
 echo "Done."
 echo ""
+
+exit $STATUS
+
